services:
  orderingserviceapi:
    image: orderingserviceapi
    build:
      context: .
      dockerfile: src/OrderingService/Ordering.Service.Api/Dockerfile
      args:
        - configuration=Debug
    ports:
      - "6001:8080"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings__OrderingDb=Host=orderingdb;Port=5432;Database=orderingdb;Username=postgres;Password=devpassword;
    volumes:
      - ~/.vsdbg:/remote_debugger:rw