@HostAddress = http://localhost:5003

POST {{HostAddress}}/api/auth/register
Content-Type: application/json

{
  "email": "jane@example.com",
  "password": "Customer123!"
}

###

POST {{HostAddress}}/api/auth/login
Content-Type: application/json

{
  "email": "jane@example.com",
  "password": "Customer123!"
}

###
